package Component.Devs;


import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class ControlController extends ViewableDigraph	{

  private SensorController z0;
  private SensorController z1;
  private SensorController z2;
  
  private SegmentController x0;
  private SegmentController x1;
  private SegmentController x2;
  
  private LineController y0;
  
  public ControlController() {	
		super ( "ControlController" );

    addInport ( "tensionIn0" );
    addInport ( "tensionIn1" );
    addInport ( "tensionIn2" );
    addOutport ( "networkState" );
    
    add ( z0 = new SensorController ( "z0", 33 ) );
    add ( z1 = new SensorController ( "z1", 13 ) );
    add ( z2 = new SensorController ( "z2", 13 ) );
    add ( x0 = new SegmentController ( "x0" ) );
    add ( x1 = new SegmentController ( "x1" ) );
    add ( x2 = new SegmentController ( "x2" ) );
    add ( y0 = new LineController ( "y0" ) );
    
    addCoupling ( this, "tensionIn0", z0, "tension" );
    addCoupling ( this, "tensionIn1", z1, "tension" );
    addCoupling ( this, "tensionIn2", z2, "tension" );
    
    addCoupling ( z0, "state", x0, "stateIn" ); 
    addCoupling ( x0, "stateOut", y0, "stateIn0" );
    
    addCoupling ( z1, "state", x1, "stateIn" ); 
    addCoupling ( x1, "stateOut", y0, "stateIn1" );
    
    addCoupling ( z2, "state", x2, "stateIn" ); 
    addCoupling ( x2, "stateOut", y0, "stateIn2" );
    
    addCoupling ( y0, "stateOut", this, "networkState" );
    
	}

  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(882, 462);
        ((ViewableComponent)withName("Sensor z2 13.0")).setPreferredLocation(new Point(11, 290));
        ((ViewableComponent)withName("LineController y0")).setPreferredLocation(new Point(482, 218));
        ((ViewableComponent)withName("Sensor z1 13.0")).setPreferredLocation(new Point(9, 208));
        ((ViewableComponent)withName("Sensor z0 33.0")).setPreferredLocation(new Point(10, 133));
        ((ViewableComponent)withName("SegmentController x2")).setPreferredLocation(new Point(211, 290));
        ((ViewableComponent)withName("SegmentController x1")).setPreferredLocation(new Point(211, 208));
        ((ViewableComponent)withName("SegmentController x0")).setPreferredLocation(new Point(209, 132));
    }
}
