package Component.Devs;


import Component.Devs.control.ControlController;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class CoupledController extends ViewableDigraph	{

  private final SimulatorController sc;
  
  private final ControlController cc;

  public CoupledController() {	
		super ( "CoupledController " );
		
    addOutport ( "out" );
    
    add ( sc = new SimulatorController () );
    add ( cc = new ControlController () );
    
    addCoupling ( sc, "tension0", cc, "tensionIn0" );
    addCoupling ( sc, "tension1", cc, "tensionIn1" );
    addCoupling ( sc, "tension2", cc, "tensionIn2" );
    
    addCoupling ( cc, "networkState", this, "out" );
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1441, 548);
        ((ViewableComponent)withName("SimulatorController")).setPreferredLocation(new Point(15, 24));
        ((ViewableComponent)withName("ControlController")).setPreferredLocation(new Point(543, 24));
    }
}
