package Component.Devs;


import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class CoupledController extends ViewableDigraph	{

  private final GeneratorController gc;
  
  private final ControlController cc;

  public CoupledController() {	
		super ( "CoupledController" );
		
    addOutport ( "out" );
    
    add ( gc = new GeneratorController () );
    add ( cc = new ControlController () );
    
    addCoupling ( gc, "tension0", cc, "tensionIn0" );
    addCoupling ( gc, "tension1", cc, "tensionIn1" );
    addCoupling ( gc, "tension2", cc, "tensionIn2" );
    
    addCoupling ( cc, "networkState", this, "out" );
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1771, 539);
        ((ViewableComponent)withName("GeneratorController")).setPreferredLocation(new Point(9, 18));
        ((ViewableComponent)withName("ControlController")).setPreferredLocation(new Point(737, 18));
    }
}
