/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import Component.Devs.simulator.ElectricGenerator;
import Component.Devs.simulator.fail.FailureGenerator;
import Component.Devs.simulator.fail.ResumeGenerator;
import java.awt.Dimension;
import java.awt.Point;
import static model.modeling.DevsInterface.INFINITY;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class GeneratorController extends ViewableDigraph{

  private final ElectricGenerator e0;
  private final FailureGenerator f0;
  private final ResumeGenerator r0;

  public GeneratorController() {
    super ( "GeneratorController" );
    addOutport ( "out" );
    add ( e0 = new ElectricGenerator ( "e0", 33 ) );
    add ( f0 = new FailureGenerator ( "f0" ) );
    add ( r0 = new ResumeGenerator ( "r0" ) );
    
    addCoupling ( e0, "response", f0, "state" );
    addCoupling ( e0, "response", r0, "state" );
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    
    addCoupling ( e0, "out", this, "out" );
  }
  
  /**
   * Automatically generated by the SimView program.
   * Do not edit this manually, as such changes will get overwritten.
   */
  @Override
  public void layoutForSimView()
  {
    preferredSize = new Dimension(937, 468);
    ((ViewableComponent)withName("e0 Eg")).setPreferredLocation(new Point(378, 155));
    ((ViewableComponent)withName("r0 Resume")).setPreferredLocation(new Point(217, 259));
    ((ViewableComponent)withName("f0 Fail")).setPreferredLocation(new Point(214, 59));
  }
}
