/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class GeneratorCoupled extends ViewableDigraph {

  private final GeneratorOk generatorOk;
  private final GeneratorFail generatorFail;

  public GeneratorCoupled ( String g0, int i, int i0 ) {
    super ( String. format ( "Generator Coupled %s", g0 ) );
    addOutport ( "out" );
    add ( generatorOk = new GeneratorOk ( g0, i, i0 ) );
    add ( generatorFail = new GeneratorFail ( g0, i, i0 ) );
    addCoupling ( generatorOk, "out", this, "out" );
    addCoupling ( generatorFail, "out", this, "out" );
  }
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(193, 144);
        ((ViewableComponent)withName("Generator OK g0")).setPreferredLocation(new Point(11, 28));
        ((ViewableComponent)withName("Generator Fail g0")).setPreferredLocation(new Point(12, 85));
    }
}
