package Component.Devs;


import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class GeneratorController extends ViewableDigraph	{
  
  private Generator g0;
  private Transformator t0;
  private Transformator t1;
  private Transformator t2;
  
  public GeneratorController () {	
		super ( "GeneratorController" );
		
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    
    add ( g0 = new Generator ( "g0", 3, 33 ) );

    add ( t0 = new Transformator ( "t0", 3, 33, 33 ) );
    add ( t1 = new Transformator ( "t1", 3, 33, 13 ) );
    add ( t2 = new Transformator ( "t2", 3, 33, 13 ) );
    
    addCoupling ( g0, "out", t0, "in" );
    addCoupling ( g0, "out", t1, "in" );
    addCoupling ( g0, "out", t2, "in" );
    
    addCoupling ( t0, "out", this, "tension0" );
    addCoupling ( t1, "out", this, "tension1" );
    addCoupling ( t2, "out", this, "tension2" );
    
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(420, 350);
        ((ViewableComponent)withName("g0")).setPreferredLocation(new Point(15, 150));
        ((ViewableComponent)withName("t0")).setPreferredLocation(new Point(151, 33));
        ((ViewableComponent)withName("t1")).setPreferredLocation(new Point(149, 150));
        ((ViewableComponent)withName("t2")).setPreferredLocation(new Point(149, 265));
    }
}
