package Component.Devs;


import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class GeneratorController extends ViewableDigraph	{
  
  private GeneratorCoupled g0;
  private TransformatorCoupled t0;
  private TransformatorCoupled t1;
  private TransformatorCoupled t2;
  
  public GeneratorController () {	
		super ( String. format ( "GeneratorController" ) );
		
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    
    add ( g0 = new GeneratorCoupled ( "g0", 3, 33 ) );

    add ( t0 = new TransformatorCoupled ( "t0", 3, 33, 33 ) );
    add ( t1 = new TransformatorCoupled ( "t1", 3, 33, 13 ) );
    add ( t2 = new TransformatorCoupled ( "t2", 3, 33, 13 ) );
    
    addCoupling ( g0, "out", t0, "in" );
    addCoupling ( g0, "out", t1, "in" );
    addCoupling ( g0, "out", t2, "in" );
    
    addCoupling ( t0, "out", this, "tension0" );
    addCoupling ( t1, "out", this, "tension1" );
    addCoupling ( t2, "out", this, "tension2" );
    
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(678, 463);
        ((ViewableComponent)withName("Transformator Coupled t2")).setPreferredLocation(new Point(317, 311));
        ((ViewableComponent)withName("Generator Coupled g0")).setPreferredLocation(new Point(44, 161));
        ((ViewableComponent)withName("Transformator Coupled t1")).setPreferredLocation(new Point(316, 167));
        ((ViewableComponent)withName("Transformator Coupled t0")).setPreferredLocation(new Point(316, 23));
    }
}
