package Component.Devs;


import Component.Devs.operational.SimulatorCoupled;
import Component.Devs.control.ControlCoupled;
import Component.Devs.registrator.RegistratorAtomic;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class GeneralCoupled extends ViewableDigraph	{

  private final SimulatorCoupled sc;
  
  private final ControlCoupled cc;
  private final RegistratorAtomic rc;

  public GeneralCoupled() {	
		super ( "CoupledController" );
    addOutport ( "state" );
    add ( rc = new RegistratorAtomic ( "r0" ) );
    add ( sc = new SimulatorCoupled ( "s0" ) );
    add ( cc = new ControlCoupled ( "c0" ) );
    
    addCoupling ( sc, "tension0", cc, "tension0" );
    addCoupling ( sc, "tension1", cc, "tension1" );
    addCoupling ( sc, "tension2", cc, "tension2" );
    
    addCoupling ( cc, "state", this, "state" );
    addCoupling ( sc, "log", rc, "in" );
    addCoupling ( cc, "log", rc, "in" );
  }
  
  
  /**
   * Automatically generated by the SimView program.
   * Do not edit this manually, as such changes will get overwritten.
   */
  @Override
  public void layoutForSimView()
  {
      preferredSize = new Dimension(1019, 909);
      ((ViewableComponent)withName("ControlController c0")).setPreferredLocation(new Point(570, 28));
      ((ViewableComponent)withName("SimulatorCoupled s0")).setPreferredLocation(new Point(14, 29));
      ((ViewableComponent)withName("RegistratorAtomic r0")).setPreferredLocation(new Point(783, 580));
  }
}
