/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import Component.Devs.operational.TransformatorController;
import Component.Devs.operational.GeneratorController;
import Component.Devs.operational.TransformatorController1;
import Component.Devs.operational.TransformatorController2;
import Component.Devs.operational.TransformatorController3;
import Component.Devs.registrator.RegistratorController;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorController extends ViewableDigraph{

  private final GeneratorController cs0;
  private final TransformatorController cs1;
  private final TransformatorController cs2;
  private final TransformatorController cs3;
  private BufferedWriter output;


  public SimulatorController () {
    super ( "SimulatorController" );
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    addOutport ( "response" );
    add ( cs0 = new GeneratorController ( "eg0" ) );
    add ( cs1 = new TransformatorController1 ( "et1", 33d, 33d ) );
    add ( cs2 = new TransformatorController2 ( "et2", 13d, 33d ) );
    add ( cs3 = new TransformatorController3 ( "et3", 13d, 33d ) );
    addCoupling ( cs0, "out", cs1, "in" );
    addCoupling ( cs0, "out", cs2, "in" );
    addCoupling ( cs0, "out", cs3, "in" );
    addCoupling ( cs1, "out", this, "tension0" );
    addCoupling ( cs2, "out", this, "tension1" );
    addCoupling ( cs3, "out", this, "tension2" );
    addCoupling ( cs1, "response", this, "response" );
    addCoupling ( cs2, "response", this, "response" );
    addCoupling ( cs3, "response", this, "response" );
  }
  
  public void reportTo ( RegistratorController rc ) {
    addCoupling ( cs1, "response", rc, "in" );
    addCoupling ( cs1, "response", rc, "in" );
    addCoupling ( cs1, "response", rc, "in" );
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(931, 617);
        ((ViewableComponent)withName("TransformatorController.et3")).setPreferredLocation(new Point(460, 409));
        ((ViewableComponent)withName("TransformatorController.et2")).setPreferredLocation(new Point(460, 218));
        ((ViewableComponent)withName("TransformatorController.et1")).setPreferredLocation(new Point(460, 29));
        ((ViewableComponent)withName("GeneratorController.eg0")).setPreferredLocation(new Point(28, 219));
    }

  
}
