/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import Component.Devs.lib.DevRegistry;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorController extends ViewableDigraph{

  public SimulatorController() {
    super (DevRegistry.register ( SimulatorController.class ) );
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    add ( new CoupledSimulator ( new ElectricGenerator ( 33 ) ) );
    add ( new CoupledSimulator ( new ElectricTransformator ( 33, 13 ) ) );
    add ( new CoupledSimulator ( new ElectricTransformator ( 33, 13 ) ) );
    add ( new CoupledSimulator ( new ElectricTransformator ( 33, 13 ) ) );
  }
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(811, 502);
        ((ViewableComponent)withName("CoupledSimulator1")).setPreferredLocation(new Point(514, 25));
        ((ViewableComponent)withName("CoupledSimulator0")).setPreferredLocation(new Point(120, 125));
        ((ViewableComponent)withName("CoupledSimulator3")).setPreferredLocation(new Point(514, 438));
        ((ViewableComponent)withName("CoupledSimulator2")).setPreferredLocation(new Point(514, 234));
    }
}
