/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import Component.Devs.simulator.ElectricGenerator;
import Component.Devs.simulator.ElectricTransformator;
import Component.Devs.simulator.fail.FailureGenerator;
import Component.Devs.simulator.fail.RestoreGenerator;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorController extends ViewableDigraph{

  private final ElectricGenerator cs0;
  private final ElectricTransformator cs1;
  private final ElectricTransformator cs2;
  private final ElectricTransformator cs3;


  public SimulatorController() {
    super ( "SimulatorController" );
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    add ( cs0 = new ElectricGenerator ( "Eg0", 33 ) );
    setup ( cs0 );
    add ( cs1 = new ElectricTransformator ( "Et1", 33, 13 ) );
    setup ( cs1 );
    add ( cs2 = new ElectricTransformator ( "Et2", 33, 13 ) );
    setup ( cs2 );
    add ( cs3 = new ElectricTransformator ( "Et3", 33, 13 ) );
    setup ( cs3 );
    addCoupling ( cs0, "out", cs1, "in" );
    addCoupling ( cs0, "out", cs2, "in" );
    addCoupling ( cs0, "out", cs3, "in" );
    addCoupling ( cs1, "out", this, "tension0" );
    addCoupling ( cs2, "out", this, "tension1" );
    addCoupling ( cs3, "out", this, "tension2" );
  }
  

  private void setup ( ElectricGenerator source ) {
    add ( source );
    FailureGenerator fail = new FailureGenerator ( source. getName () );
    add ( fail );
    RestoreGenerator resume = new RestoreGenerator ( source. getName () );
    add ( resume );
    addCoupling ( source, "response", fail, "state" );
    addCoupling ( source, "response", resume, "state" );
    addCoupling ( fail, "response", source, "state" );
    addCoupling ( resume, "response", source, "state" );
  }
  
  private void setup ( ElectricTransformator source ) {
    add ( source );
    FailureGenerator fail = new FailureGenerator ( source. getName () );
    add ( fail );
    RestoreGenerator resume = new RestoreGenerator ( source. getName () );
    add ( resume );
    addCoupling ( source, "response", fail, "state" );
    addCoupling ( source, "response", resume, "state" );
    addCoupling ( fail, "response", source, "state" );
    addCoupling ( resume, "response", source, "state" );
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(569, 513);
        ((ViewableComponent)withName("Et2 Fail")).setPreferredLocation(new Point(254, 179));
        ((ViewableComponent)withName("Et2")).setPreferredLocation(new Point(254, 232));
        ((ViewableComponent)withName("Et1")).setPreferredLocation(new Point(254, 71));
        ((ViewableComponent)withName("Eg0 Eg")).setPreferredLocation(new Point(27, 233));
        ((ViewableComponent)withName("Et3")).setPreferredLocation(new Point(254, 393));
        ((ViewableComponent)withName("Et3 Fail")).setPreferredLocation(new Point(254, 339));
        ((ViewableComponent)withName("Eg0 Eg Resume")).setPreferredLocation(new Point(27, 287));
        ((ViewableComponent)withName("Et2 Resume")).setPreferredLocation(new Point(254, 286));
        ((ViewableComponent)withName("Et1 Fail")).setPreferredLocation(new Point(254, 18));
        ((ViewableComponent)withName("Eg0 Eg Fail")).setPreferredLocation(new Point(27, 179));
        ((ViewableComponent)withName("Et1 Resume")).setPreferredLocation(new Point(254, 125));
        ((ViewableComponent)withName("Et3 Resume")).setPreferredLocation(new Point(254, 448));
    }
}
