/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import Component.Devs.simulator.ElectricGenerator;
import Component.Devs.simulator.ElectricTransformator;
import Component.Devs.simulator.fail.FailureGenerator;
import Component.Devs.simulator.fail.RestoreGenerator;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class TransformatorController extends ViewableDigraph{

  private ElectricTransformator e0;
  private FailureGenerator f0;
  private RestoreGenerator r0;

  public TransformatorController( String n ) {
    super ( String. format ( "TransformatorController.%s", n ) );
    addOutport ( "out" );
    addInport ( "in" );
    add ( e0 = new ElectricTransformator ( String. format ( "%s.eg0", n ), 33d, 13d ) );
    add ( f0 = new FailureGenerator ( String. format ( "%s.fg0", n ) ) );
    add ( r0 = new RestoreGenerator ( String. format ( "%s.rg0", n ) ) );
    
    addCoupling ( this, "in", e0, "in" );
    
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( f0, "response", r0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    addCoupling ( r0, "response", f0, "state" );
    
    addCoupling ( e0, "out", this, "out" );
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(362, 178);
        ((ViewableComponent)withName("et1.eg0")).setPreferredLocation(new Point(107, 77));
        ((ViewableComponent)withName("et1.fg0 Fail")).setPreferredLocation(new Point(-9, 26));
        ((ViewableComponent)withName("et1.rg0 Restore")).setPreferredLocation(new Point(-9, 121));
        
    }
}
