/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class TransformatorCoupled extends ViewableDigraph {

  private final TransformatorOk transformatorOk;
  private final TransformatorFail transformatorFail;

  public TransformatorCoupled ( String g0, int i, int i0, int i1 ) {
    super ( String. format ( "Transformator Coupled %s", g0 ) );
    addOutport ( "out" );
    addInport ( "in" );
    add ( transformatorOk = new TransformatorOk ( g0, i, i0, i1 ) );
    add ( transformatorFail = new TransformatorFail ( g0, i, i0, i1 ) );
    addCoupling ( this, "in", transformatorOk, "in" );
    addCoupling ( this, "in", transformatorFail, "in" );
    addCoupling ( transformatorOk, "out", this, "out" );
    addCoupling ( transformatorFail, "out", this, "out" );
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(276, 138);
        ((ViewableComponent)withName("Trasnformator Fail t0")).setPreferredLocation(new Point(19, 85));
        ((ViewableComponent)withName("Trasnformator t0")).setPreferredLocation(new Point(22, 21));
    }
}
