/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.simulator;

import Component.Devs.simulator.fail.FailGenerator;
import Component.Devs.simulator.fail.ResumeGenerator;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class CoupledSimulator extends ViewableDigraph {

  private final FailGenerator fail;
  
  private final ResumeGenerator resume;
  
  public CoupledSimulator ( String n, ViewableAtomic e ) {
    super ( n );
    addOutport ( "out" );
    addInport ( "in" );
    add ( e );
    add ( fail = new FailGenerator ( String. format ( "%s/%s", n, "fg0" ) ) );
    add ( resume = new ResumeGenerator ( String. format ( "%s/%s", n, "fg0" ) ) );
    addCoupling ( e, "out", this, "out" );
    addCoupling ( e, "out", fail, "in" );
    addCoupling ( e, "out", resume, "in" );
    addCoupling ( fail, "out", e, "in" );
    addCoupling ( resume, "out", e, "in" );
  }
  
  
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(248, 202);
        ((ViewableComponent)withName("FailGenerator2")).setPreferredLocation(new Point(-6, 19));
        ((ViewableComponent)withName("ElectricTransformator1")).setPreferredLocation(new Point(-6, 77));
        ((ViewableComponent)withName("ResumeGenerator2")).setPreferredLocation(new Point(-5, 136));
    }
}
