/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.simulator;

import Component.Devs.simulator.fail.FailGenerator;
import Component.Devs.simulator.fail.ResumeGenerator;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class CoupledSimulator extends ViewableDigraph {

  private final FailGenerator fail;
  
  private final ResumeGenerator resume;
  
  public CoupledSimulator ( String n, ViewableAtomic e ) {
    super ( n );
    addOutport ( "out" );
    addInport ( "in" );
    add ( e );
    add ( fail = new FailGenerator ( String. format ( "%s/%s", n, "fg0" ) ) );
    add ( resume = new ResumeGenerator ( String. format ( "%s/%s", n, "rg0" ) ) );
    addCoupling ( e, "out", this, "out" );
    addCoupling ( e, "out", fail, "in" );
    addCoupling ( e, "out", resume, "in" );
    addCoupling ( this, "in", e, "in" );
    addCoupling ( fail, "out", e, "state" );
    addCoupling ( resume, "out", e, "state" );
  }
  
  
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(389, 145);
        ((ViewableComponent)withName("Et2")).setPreferredLocation(new Point(125, 60));
        ((ViewableComponent)withName("Cs2/fg0")).setPreferredLocation(new Point(-4, 15));
        ((ViewableComponent)withName("Cs2/rg0")).setPreferredLocation(new Point(-6, 87));
    }
}
