/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.simulator;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorController extends ViewableDigraph{

  private final CoupledSimulator cs0;
  private final CoupledSimulator cs1;
  private final CoupledSimulator cs2;
  private final CoupledSimulator cs3;

  public SimulatorController() {
    super ( "SimulatorController" );
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );
    add ( cs0 = new CoupledSimulator ( "Cs0", new ElectricGenerator ( "Eg0", 33 ) ) );
    add ( cs1 = new CoupledSimulator ( "Cs1", new ElectricTransformator ( "Et1", 33, 13 ) ) );
    add ( cs2 = new CoupledSimulator ( "Cs2", new ElectricTransformator ( "Et2", 33, 13 ) ) );
    add ( cs3 = new CoupledSimulator ( "Cs3", new ElectricTransformator ( "Et3", 33, 13 ) ) );
    addCoupling ( cs0, "out", cs1, "in" );
    addCoupling ( cs0, "out", cs2, "in" );
    addCoupling ( cs0, "out", cs3, "in" );
    addCoupling ( cs1, "out", this, "tension0" );
    addCoupling ( cs2, "out", this, "tension1" );
    addCoupling ( cs3, "out", this, "tension2" );
  }
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(845, 502);
        ((ViewableComponent)withName("Cs1")).setPreferredLocation(new Point(381, 25));
        ((ViewableComponent)withName("Cs0")).setPreferredLocation(new Point(18, 201));
        ((ViewableComponent)withName("Cs3")).setPreferredLocation(new Point(380, 350));
        ((ViewableComponent)withName("Cs2")).setPreferredLocation(new Point(380, 201));
    }
}
