/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.operational.ElectricGenerator;
import Component.Devs.operational.fail.FailureGenerator;
import Component.Devs.operational.fail.RestoreGenerator;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class GeneratorController extends ViewableDigraph{

  private ElectricGenerator e0, e1, e2;
  private FailureGenerator f0;
  private RestoreGenerator r0;

  public GeneratorController () {
    this ( "g0" );
  }
  
  public GeneratorController ( String n ) {
    super ( String. format ( "GeneratorController.%s", n ) );
    addOutport ( "out" );
    
    add ( e0 = new ElectricGenerator ( String. format ( "%s.eg0", n ), 33d ) );
    add ( f0 = new FailureGenerator ( String. format ( "%s.fg0", n ) ) );
    add ( r0 = new RestoreGenerator ( String. format ( "%s.rg0", n ) ) );
    
    addCoupling ( e0, "out", this, "out" );
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( f0, "response", r0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    addCoupling ( r0, "response", f0, "state" );

  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(416, 178);
        ((ViewableComponent)withName("RG.eg0.rg0")).setPreferredLocation(new Point(2, 116));
        ((ViewableComponent)withName("FG.eg0.fg0")).setPreferredLocation(new Point(2, 19));
        ((ViewableComponent)withName("EG.eg0.eg0")).setPreferredLocation(new Point(162, 68));
    }
}
