/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.operational.ElectricGenerator;
import Component.Devs.operational.fail.FailureGenerator;
import Component.Devs.operational.fail.RestoreGenerator;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class GeneratorController extends ViewableDigraph{

  private ElectricGenerator e0, e1, e2;
  private FailureGenerator f0;
  private RestoreGenerator r0;

  public GeneratorController () {
    this ( "g0" );
  }
  
  public GeneratorController ( String n ) {
    super ( String. format ( "GeneratorController %s", n ) );
    
    addOutport ( "otension" );
    addOutport ( "log" );
    
    add ( e0 = new ElectricGenerator ( n + "/g0", 33d ) );
    add ( f0 = new FailureGenerator ( n + "/f0" ) );
    add ( r0 = new RestoreGenerator ( n + "/r0", 3, 120 ) );
    
    addCoupling ( e0, "otension", this, "otension" );
    addCoupling ( e0, "log", this, "log" );
    
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( f0, "response", r0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    addCoupling ( r0, "response", f0, "state" );

  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(363, 257);
        ((ViewableComponent)withName("RestoreGenerator g0/r0")).setPreferredLocation(new Point(41, 144));
        ((ViewableComponent)withName("ElectricGenerator g0/g0(33.0)")).setPreferredLocation(new Point(-2, 19));
        ((ViewableComponent)withName("FailureGenerator g0/f0")).setPreferredLocation(new Point(9, 79));
    }
}
