/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.registrator.RegistratorController;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorController extends ViewableDigraph{

  private final GeneratorController cs0;
  
  private final TransformatorController cs1;
  
  private final TransformatorController cs2;
  
  private final TransformatorController cs3;

  public SimulatorController ( String n ) {
    super ( String. format ( "SimulatorController %s", n ) );
    
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );

    addOutport ( "log" );
    
    add ( cs0 = new GeneratorController ( "g0" ) );
    add ( cs1 = new TransformatorController1 ( "t1", 33d, 33d ) );
    add ( cs2 = new TransformatorController2 ( "t2", 13d, 33d ) );
    add ( cs3 = new TransformatorController3 ( "t3", 13d, 33d ) );
    
    addCoupling ( cs0, "otension", cs1, "tension" );
    addCoupling ( cs0, "otension", cs2, "tension" );
    addCoupling ( cs0, "otension", cs3, "tension" );

    addCoupling ( cs1, "otension", this, "tension0" );
    addCoupling ( cs2, "otension", this, "tension1" );
    addCoupling ( cs3, "otension", this, "tension2" );

    addCoupling ( cs0, "log", this, "log" );
    addCoupling ( cs1, "log", this, "log" );
    addCoupling ( cs2, "log", this, "log" );
    addCoupling ( cs3, "log", this, "log" );
  }
  
  public void reportTo ( RegistratorController rc ) {
    addCoupling ( this, "log", rc, "in" );
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(981, 650);
        ((ViewableComponent)withName("GeneratorController g0")).setPreferredLocation(new Point(42, 33));
        ((ViewableComponent)withName("TransformatorController t1")).setPreferredLocation(new Point(420, 34));
        ((ViewableComponent)withName("TransformatorController t3")).setPreferredLocation(new Point(421, 438));
        ((ViewableComponent)withName("TransformatorController t2")).setPreferredLocation(new Point(420, 238));
    }
}
