/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.operational.probability.distribution.Weibull;
import Component.Devs.registrator.RegistratorAtomic;
import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class SimulatorCoupled extends ViewableDigraph{

  private final GeneratorCoupled cs0;
  
  private final TransformatorCoupled cs1;
  
  private final TransformatorCoupled cs2;
  
  private final TransformatorCoupled cs3;

  public SimulatorCoupled ( String n ) {
    super ( String. format ( "SimulatorCoupled %s", n ) );
    
    addOutport ( "tension0" );
    addOutport ( "tension1" );
    addOutport ( "tension2" );

    addOutport ( "log" );
    
    add ( cs0 = new GeneratorCoupled ( "g0", 33d ) );
    cs0. preventFailure ( true );
    add ( cs1 = new TransformatorCoupled1 ( "t1", 33d, 33d ) );
    cs1. preventFailure ( true );
    add ( cs2 = new TransformatorCoupled2 ( "t2", 33d, 13d ) );
    cs2. preventFailure ( true );
    add ( cs3 = new TransformatorCoupled3 ( "t3", 33d, 13d ) );
    cs3. event ( 10, 20, 0 );
    addCoupling ( cs0, "otension", cs1, "tension" );
    addCoupling ( cs1, "otension", cs2, "tension" );
    addCoupling ( cs1, "otension", cs3, "tension" );

    addCoupling ( cs1, "otension", this, "tension0" );
    addCoupling ( cs2, "otension", this, "tension1" );
    addCoupling ( cs3, "otension", this, "tension2" );

    addCoupling ( cs0, "log", this, "log" );
    addCoupling ( cs1, "log", this, "log" );
    addCoupling ( cs2, "log", this, "log" );
    addCoupling ( cs3, "log", this, "log" );
  }
  
  public void reportTo ( RegistratorAtomic rc ) {
    addCoupling ( this, "log", rc, "in" );
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(538, 863);
        ((ViewableComponent)withName("TransformatorCoupled t2")).setPreferredLocation(new Point(15, 445));
        ((ViewableComponent)withName("TransformatorCoupled t3")).setPreferredLocation(new Point(16, 649));
        ((ViewableComponent)withName("TransformatorCoupled t1")).setPreferredLocation(new Point(15, 238));
        ((ViewableComponent)withName("GeneratorCoupled g0")).setPreferredLocation(new Point(15, 31));
    }
}
