/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;

/**
 *
 * @author sysadmin
 */
public class TransformatorController3 extends TransformatorController {

  public TransformatorController3 ( String et, double d0, double d1) {
    super ( et, d0, d1 );
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(490, 201);
        ((ViewableComponent)withName("RestoreGenerator t3/r0")).setPreferredLocation(new Point(97, 142));
        ((ViewableComponent)withName("FailureGenerator t3/f0")).setPreferredLocation(new Point(15, 85));
        ((ViewableComponent)withName("ElectricTransformator t3/t0(13.0/33.0)")).setPreferredLocation(new Point(4, 26));
    }
}
