/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.lib.ElectricEvent;
import Component.Devs.operational.fail.FailureGenerator;
import Component.Devs.operational.fail.RestoreGenerator;
import Component.Devs.operational.probability.distribution.Uniform;
import Component.Devs.operational.probability.distribution.Weibull;
import java.awt.Dimension;
import java.awt.Point;
import java.util.LinkedHashMap;
import static model.modeling.DevsInterface.INFINITY;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class TransformatorCoupled extends ViewableDigraph {

  private Weibull fail = new Weibull ( 779.74, 0.34, true );
  
  private Uniform restore = new Uniform ( 0, 554, true );
  
  private Uniform level;
  
  private ElectricTransformator e0;
  
  private FailureGenerator f0;
  
  private RestoreGenerator r0;
  
  private final LinkedHashMap < Double, ElectricEvent > events = new LinkedHashMap <> ();
  
  private boolean preventFailure = false;
  
  public TransformatorCoupled () {
    this ( "t0", 13d, 33d );
  }
  
  public TransformatorCoupled( String n, double t0, double t1 ) {
    super ( String. format ( "TransformatorCoupled %s", n ) );
    addInport ( "tension" );
    addOutport ( "otension" );
    addOutport ( "log" );
    
    add ( e0 = new ElectricTransformator ( "t0", t0, t1 ) );
    
    add ( f0 = new FailureGenerator ( "f0" ) );
    
    level = new Uniform ( 0, t1, true );
    
    add ( r0 = new RestoreGenerator ( "r0" ) );
    
    addCoupling ( this, "tension", e0, "tension" );
    addCoupling ( e0, "otension", this, "otension" );
    
    addCoupling ( e0, "log", this, "log" );
    
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( f0, "response", r0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    addCoupling ( r0, "response", f0, "state" );
  }
  
  public ElectricEvent event () {
    if ( preventFailure ) {
      return new ElectricEvent ( INFINITY, 0 );
    }
    if ( events. isEmpty () ) {
      return new ElectricEvent ( fail. inverse ( Math. random () ), restore. inverse ( Math. random () ), level. inverse ( Math. random () ) );
    } 
    return events. remove ( events. keySet (). toArray ( new Double [ 0 ] ) [ 0 ] );
  }
  
  public ElectricEvent event ( double start, double duration ) {
    ElectricEvent event = new ElectricEvent ( start, duration );
    event. level = level. inverse ( Math. random () ) ;
    events. put ( start, event );
    return event;
  }
  
  public ElectricEvent event ( double start, double duration, double level ) {
    ElectricEvent event = event ( start, duration );
    event. level = level;
    return event;
  }
  
  public void preventFailure ( boolean b ) {
    preventFailure = b;
  }

  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 332);
        ((ViewableComponent)withName("ElectricTransformator t0(13.0/33.0)")).setPreferredLocation(new Point(75, 47));
        ((ViewableComponent)withName("FailureGenerator f0")).setPreferredLocation(new Point(82, 138));
        ((ViewableComponent)withName("RestoreGenerator r0")).setPreferredLocation(new Point(81, 232));
    }

}
