/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;

/**
 *
 * @author sysadmin
 */
public class TransformatorCoupled2 extends TransformatorCoupled {

  public TransformatorCoupled2 ( String et, double d0, double d1) {
    super ( et, d0, d1 );
  } 
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(445, 200);
        ((ViewableComponent)withName("FailureGenerator f0")).setPreferredLocation(new Point(0, 139));
        ((ViewableComponent)withName("ElectricTransformator t0(33.0/13.0)")).setPreferredLocation(new Point(-13, 21));
        ((ViewableComponent)withName("RestoreGenerator r0")).setPreferredLocation(new Point(1, 79));
    }
}
