/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import Component.Devs.operational.ElectricTransformator;
import Component.Devs.operational.fail.FailureGenerator;
import Component.Devs.operational.fail.RestoreGenerator;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 *
 * @author sysadmin
 */
public class TransformatorController extends ViewableDigraph{

  private ElectricTransformator e0;
  private FailureGenerator f0;
  private RestoreGenerator r0;

  
  public TransformatorController () {
    this ( "t0", 13d, 33d );
  }
  
  public TransformatorController( String n, double t0, double t1 ) {
    super ( String. format ( "TransformatorController.%s", n ) );
    addOutport ( "out" );
    addOutport ( "response" );
    addInport ( "in" );
    add ( e0 = new ElectricTransformator ( String. format ( "%s.et0", n ), t0, t1 ) );
    add ( f0 = new FailureGenerator ( String. format ( "%s.fg0", n ) ) );
    add ( r0 = new RestoreGenerator ( String. format ( "%s.rg0", n ) ) );
    
    addCoupling ( this, "in", e0, "in" );
    
    addCoupling ( f0, "response", e0, "state" );
    addCoupling ( f0, "response", r0, "state" );
    addCoupling ( r0, "response", e0, "state" );
    addCoupling ( r0, "response", f0, "state" );

    addCoupling ( e0, "out", this, "out" );
    addCoupling ( f0, "response", this, "response" );
    addCoupling ( r0, "response", this, "response" );
    addCoupling ( e0, "response", this, "response" );
  }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(399, 178);
        ((ViewableComponent)withName("FG.et1.fg0")).setPreferredLocation(new Point(-8, 20));
        ((ViewableComponent)withName("RG.et1.rg0")).setPreferredLocation(new Point(-8, 124));
        ((ViewableComponent)withName("et1.et0")).setPreferredLocation(new Point(108, 77));
    }

}
