/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;

/**
 *
 * @author sysadmin
 */
public class TransformatorController3 extends TransformatorController {

  public TransformatorController3 ( String et, double d0, double d1) {
    super ( et, d0, d1 );
  }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(399, 178);
        ((ViewableComponent)withName("FG.et3.fg0")).setPreferredLocation(new Point(-9, 24));
        ((ViewableComponent)withName("et3.et0")).setPreferredLocation(new Point(107, 70));
        ((ViewableComponent)withName("RG.et3.rg0")).setPreferredLocation(new Point(-9, 117));
    }
}
