/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Component.Devs.operational;

import java.awt.Dimension;
import java.awt.Point;
import view.modeling.ViewableComponent;

/**
 *
 * @author sysadmin
 */
public class TransformatorController1 extends TransformatorController {

  public TransformatorController1 ( String et, double d0, double d1) {
    super ( et, d0, d1 );
  }
  
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(490, 196);
        ((ViewableComponent)withName("ElectricTransformator t1/t0(33.0/33.0)")).setPreferredLocation(new Point(14, 20));
        ((ViewableComponent)withName("RestoreGenerator t1/r0")).setPreferredLocation(new Point(111, 134));
        ((ViewableComponent)withName("FailureGenerator t1/f0")).setPreferredLocation(new Point(26, 77));
    }
}
