package CCA.AgentDiffusionNotSameMap;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import model.modeling.CAModels.TwoDimCellSpace;
import model.modeling.CCAModels.CCAModel;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class AgentSpace extends CCAModel {

	private final String[] statusCXCL12 = {"EMPTY", "EMPTY", "CXCL12"};

	public AgentSpace() {
		this(10, 30);
	}

	public AgentSpace(int x, int y) {
		this(new MapRegion(x, y));
	}

	public AgentSpace(MapRegion mapR) {
		super("Chemotaxis", mapR);
		int xDim = mapR.get_num_cols();
		int yDim = mapR.get_num_rows();

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				Random randomno = new Random();
				Agent cell;
				if (j > 1) {
					cell = new Agent(i, j,
							statusCXCL12[randomno.nextInt(statusCXCL12.length)],
							1);
				} else {
					cell = new Agent(i, j, "EMPTY", 1);
				}
				addCCACell(cell);
			}
		}

		doNeighborToNeighborCoupling();

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 884);
        ((ViewableComponent)withName("Cell: 1, 3")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(300, 617));
        ((ViewableComponent)withName("Cell: 0, 4")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(178, 608));
        ((ViewableComponent)withName("Cell: 2, 2")).setPreferredLocation(new Point(17, 618));
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 0, 3")).setPreferredLocation(new Point(280, 83));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 2, 3")).setPreferredLocation(new Point(26, 418));
        ((ViewableComponent)withName("Cell: 1, 4")).setPreferredLocation(new Point(10, 251));
        ((ViewableComponent)withName("Cell: 2, 1")).setPreferredLocation(new Point(176, 388));
        ((ViewableComponent)withName("Cell: 0, 2")).setPreferredLocation(new Point(38, 739));
        ((ViewableComponent)withName("Cell: 2, 4")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Cell: 1, 2")).setPreferredLocation(new Point(202, 227));
    }
}
