package CCA.AgentDiffusionNotSameMap;

import java.awt.Dimension;
import java.awt.Point;

import model.modeling.CCAModels.CCAKIBModel;
import model.modeling.CCAModels.CCAsSpaceModel;
import model.modeling.GeoKIB.LengthUnit;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class CCA_Agent_Diffusion extends CCAsSpaceModel {

	static int sx = 6, sy = 6;
	static int sx1 = 12, sy1 = 6;
	
	static MapRegion mapR_A = new MapRegion(sx, sy, 0.01, 0.2, 0.01, 0.2,
			LengthUnit.KILOMETER);

	static MapRegion mapR_B = new MapRegion(sx1, sy1, 0, 100, 0, 200,
			LengthUnit.METER);

	private static AgentSpace cca1 = new AgentSpace(mapR_A);

	private static DiffusionSpace cca2 = new DiffusionSpace(mapR_B);

	private static CCA_Agent_KIB ccakib = new CCA_Agent_KIB(
			"Chemotaxis-KIB-Diffusion", mapR_A, mapR_B, 0, 0, 0.01, 0.01,
			LengthUnit.KILOMETER);

	public CCA_Agent_Diffusion() {
		this(cca1, cca2, ccakib);
	}

	public CCA_Agent_Diffusion(AgentSpace cca1, DiffusionSpace cca2,
			CCAKIBModel _ccaKib) {
		super("agent diffusion cca", cca1, cca2, _ccaKib);
		add(cca1);
		add(cca2);
		add(_ccaKib);

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1707, 1028);
        ((ViewableComponent)withName("Chemotaxis")).setPreferredLocation(new Point(922, 38));
        ((ViewableComponent)withName("Chemotaxis-KIB-Diffusion")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("CXCL12 Diffusion")).setPreferredLocation(new Point(50, 50));
    }
}
