package CCA.AgentDiffusionNotSameMap;

import java.awt.Dimension;
import java.awt.Point;

import model.modeling.CCAModels.CCAModel;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class DiffusionSpace extends CCAModel {

	public DiffusionSpace() {
		this(new MapRegion(10, 30));
	}

	public DiffusionSpace(int x, int y) {
		this(new MapRegion(x, y));

	}

	public DiffusionSpace(MapRegion mapR) {
		super("CXCL12 Diffusion", mapR);

		int xDim = mapR.get_num_cols();
		int yDim = mapR.get_num_rows();

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				DiffusionCell heatcell = new DiffusionCell(i, j);

				if (j == 0) {
					heatcell.isSource = 1;
				}

				addCCACell(heatcell);

			}
		}

		doNeighborToNeighborCoupling();

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this
	 * manually, as such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(536, 575);
		((ViewableComponent) withName("Cell: 0, 2"))
				.setPreferredLocation(new Point(107, 339));
		((ViewableComponent) withName("Cell: 1, 4"))
				.setPreferredLocation(new Point(50, 50));
		((ViewableComponent) withName("Cell: 1, 1"))
				.setPreferredLocation(new Point(169, 258));
		((ViewableComponent) withName("Cell: 1, 2"))
				.setPreferredLocation(new Point(50, 50));
		((ViewableComponent) withName("Cell: 0, 0"))
				.setPreferredLocation(new Point(8, 36));
		((ViewableComponent) withName("Cell: 2, 4"))
				.setPreferredLocation(new Point(124, 420));
		((ViewableComponent) withName("Cell: 0, 3"))
				.setPreferredLocation(new Point(22, 275));
		((ViewableComponent) withName("Cell: 0, 4"))
				.setPreferredLocation(new Point(-12, 297));
		((ViewableComponent) withName("Cell: 1, 0"))
				.setPreferredLocation(new Point(172, 39));
		((ViewableComponent) withName("Cell: 0, 1"))
				.setPreferredLocation(new Point(158, 269));
		((ViewableComponent) withName("Cell: 2, 3"))
				.setPreferredLocation(new Point(142, 203));
		((ViewableComponent) withName("Cell: 2, 2"))
				.setPreferredLocation(new Point(151, 295));
		((ViewableComponent) withName("Cell: 2, 0"))
				.setPreferredLocation(new Point(50, 50));
		((ViewableComponent) withName("Cell: 2, 1"))
				.setPreferredLocation(new Point(118, 329));
		((ViewableComponent) withName("Cell: 1, 3"))
				.setPreferredLocation(new Point(96, 300));
	}
}
