package CCA.BrSimulation2X7;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import model.modeling.CCAModels.CCAModel;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class AgentSpace extends CCAModel {

	private final String[] statusCXCL12 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"CXCL12"};
	private final String[] statusCXCLR4 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"CXCR4"};
	private final String[] statusCXCLR7 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
			"CXCR7"};

	public AgentSpace(String name, MapRegion mapR) {
		this(name, mapR, null);

	}

	public AgentSpace(String name, MapRegion mapR, String[][] initialStatus) {
		super(name, mapR);

		int xDim = mapR.get_num_cols();
		int yDim = mapR.get_num_rows();

		this.numCells = xDim * yDim;
		if (initialStatus == null) {
			for (int i = 0; i < xDimCellspace; i++) {
				for (int j = 0; j < yDimCellspace; j++) {
					Random randomno = new Random();
					Agent cell;
					if (i <= xDimCellspace / 3 - 1) {
						cell = new Agent(i, j, statusCXCL12[randomno
								.nextInt(statusCXCL12.length)], 360);
					} else if (i >= xDimCellspace / 3 * 2 + 1) {
						cell = new Agent(i, j, statusCXCLR7[randomno
								.nextInt(statusCXCLR7.length)], 360);
					} else {
						cell = new Agent(i, j, statusCXCLR4[randomno
								.nextInt(statusCXCLR4.length)], 360);
					}
					addCCACell(cell);
				}
			}
		} else {
			for (int i = 0; i < initialStatus.length; i++) {
				for (int j = 0; j < initialStatus[0].length; j++) {

					Agent cell = new Agent(i, j, initialStatus[i][j], 360);
					addCCACell(cell);

				}
			}

		}

		doNeighborToNeighborCoupling();

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1393, 411);
        ((ViewableComponent)withName("Cell: 5, 0")).setPreferredLocation(new Point(863, 15));
        ((ViewableComponent)withName("Cell: 6, 1")).setPreferredLocation(new Point(1046, 212));
        ((ViewableComponent)withName("Cell: 6, 0")).setPreferredLocation(new Point(1038, 12));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(146, 22));
        ((ViewableComponent)withName("Cell: 2, 1")).setPreferredLocation(new Point(305, 218));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(305, 28));
        ((ViewableComponent)withName("Cell: 4, 0")).setPreferredLocation(new Point(678, 29));
        ((ViewableComponent)withName("Cell: 3, 0")).setPreferredLocation(new Point(493, 31));
        ((ViewableComponent)withName("Cell: 4, 1")).setPreferredLocation(new Point(683, 217));
        ((ViewableComponent)withName("Cell: 5, 1")).setPreferredLocation(new Point(865, 211));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(-7, 20));
        ((ViewableComponent)withName("Cell: 3, 1")).setPreferredLocation(new Point(490, 220));
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(-23, 216));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(139, 219));
    }
}
