package CCA.BrSimulation2X7;

import java.awt.Dimension;
import java.awt.Point;

import model.modeling.CCAModels.CCAModel;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class DiffusionSpace extends CCAModel {

	public DiffusionSpace(String name, MapRegion mapR) {
		super(name, mapR);

		int xDim = mapR.get_num_cols();
		int yDim = mapR.get_num_rows();
		
		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				DCell microcell = new DCell(i, j);
				addCCACell(microcell);
			}

		}

		doNeighborToNeighborCoupling();

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1494, 377);
        ((ViewableComponent)withName("Cell: 5, 0")).setPreferredLocation(new Point(930, 16));
        ((ViewableComponent)withName("Cell: 6, 1")).setPreferredLocation(new Point(1135, 203));
        ((ViewableComponent)withName("Cell: 6, 0")).setPreferredLocation(new Point(1122, 15));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(191, 10));
        ((ViewableComponent)withName("Cell: 2, 1")).setPreferredLocation(new Point(383, 199));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(378, 12));
        ((ViewableComponent)withName("Cell: 4, 0")).setPreferredLocation(new Point(745, 12));
        ((ViewableComponent)withName("Cell: 3, 0")).setPreferredLocation(new Point(570, 14));
        ((ViewableComponent)withName("Cell: 4, 1")).setPreferredLocation(new Point(751, 201));
        ((ViewableComponent)withName("Cell: 5, 1")).setPreferredLocation(new Point(944, 201));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(-5, 9));
        ((ViewableComponent)withName("Cell: 3, 1")).setPreferredLocation(new Point(575, 200));
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(-3, 201));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(194, 198));
    }
}
