package CCA.BrSimulation2X7;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import model.modeling.CCAModels.CCAKIBModel;
import model.modeling.CCAModels.CCAModel;
import model.modeling.CCAModels.CCAsSpaceModel;
import model.modeling.GeoKIB.LengthUnit;
import model.modeling.GeoKIB.MapRegion;
import view.modeling.ViewableComponent;

public class MultiScalePDEABM extends CCAsSpaceModel {

	// private static int macroSizeX = 2;
	// private static int macroSizeY = 1;
	// private static int microSizeX = 4;
	// private static int microSizeY = 2;

	// private static int macroSizeX = 30;
	// private static int macroSizeY = 10;
	// private static int microSizeX = 60;
	// private static int microSizeY = 20;

	static MapRegion mapR_A = new MapRegion(7, 2, 0, 100, 0, 300, LengthUnit.NANOMETER);

	static MapRegion mapR_B = new MapRegion(7, 2, 0, 100, 0, 300, LengthUnit.NANOMETER);

	private static String[][] initialStatus = setInitMap(7, 2);

	private static AgentSpace agent = new AgentSpace("Agent", mapR_A, initialStatus);

	private static DiffusionSpace diffusion = new DiffusionSpace("Diffusion", mapR_B);

	private static FunctionKIB ccakib = new FunctionKIB("Chemotaxis-KIB-Diffusion", mapR_A, mapR_B, 0, 0, 0, 0,
			LengthUnit.NANOMETER, initialStatus);

	public MultiScalePDEABM() {
		this(agent, diffusion, ccakib);
	}

	public MultiScalePDEABM(AgentSpace cca1, DiffusionSpace cca2, CCAKIBModel _ccaKib) {
		super("Breast Cancer", cca1, cca2, _ccaKib);
		add(cca1);
		add(cca2);
		add(_ccaKib);

	}

//	private static String[][] setInitMap(int x, int y) {
//		String[][] initialStatus = new String[x][y];
//		final String[] statusL12 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
//				"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "CXCL12"};
//		final String[] statusX4 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
//				"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "CXCR4"};
//		final String[] statusX7 = {"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY",
//				"EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "EMPTY", "CXCR7"};
//
//		for (int i = 0; i < initialStatus.length; i++) {
//			for (int j = 0; j < initialStatus[0].length; j++) {
//				Random randomno = new Random();
//				if (i <= initialStatus.length / 3 - 1) {
//					initialStatus[i][j] = statusL12[randomno
//							.nextInt(statusL12.length)];
//				} else if (i >= initialStatus.length / 3 * 2 + 1) {
//					initialStatus[i][j] = statusX7[randomno
//							.nextInt(statusX7.length)];
//				} else {
//					initialStatus[i][j] = statusX4[randomno
//							.nextInt(statusX4.length)];
//				}
//
//			}
//		}
//		return initialStatus;
//
//	}

	private static String[][] setInitMap(int x, int y) {
		String[][] initialStatus = new String[x][y];

		for (int i = 0; i < initialStatus.length; i++) {
			for (int j = 0; j < initialStatus[0].length; j++) {
				if (i == 1) {
					initialStatus[i][j] = "CXCL12";
				} else if (i == 3) {
					initialStatus[i][j] = "CXCR4";
				} else if (i == 5) {
					initialStatus[i][j] = "CXCR7";
				} else {
					initialStatus[i][j] = "EMPTY";
				}

			}
		}
		return initialStatus;

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1705, 967);
        ((ViewableComponent)withName("Agent")).setPreferredLocation(new Point(-5, 51));
        ((ViewableComponent)withName("Diffusion")).setPreferredLocation(new Point(15, 555));
        ((ViewableComponent)withName("Chemotaxis-KIB-Diffusion")).setPreferredLocation(new Point(1331, 147));
    }
}
