package Component.Devs.control;


import Component.Devs.registrator.RegistratorAtomic;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class ControlCoupled extends ViewableDigraph	{

  private SensorAtomic z0;
  private SensorAtomic z1;
  private SensorAtomic z2;
  
  private SegmentAtomic x0;
  private SegmentAtomic x1;
  private SegmentAtomic x2;
  
  private LineAtomic y0;
  
  public ControlCoupled ( String n ) {	
		super ( String. format ( "ControlController %s", n ) );

    addInport ( "tension0" );
    addInport ( "tension1" );
    addInport ( "tension2" );
    
    addOutport ( "state" );
    
    addOutport ( "log" );
    
    add ( z0 = new SensorAtomic ( "z0", 33 ) );
    add ( z1 = new SensorAtomic ( "z1", 13 ) );
    add ( z2 = new SensorAtomic ( "z2", 13 ) );
    
    add ( x0 = new SegmentAtomic ( "x0", 0 ) );
    add ( x1 = new SegmentAtomic ( "x1", 1 ) );
    add ( x2 = new SegmentAtomic ( "x2", 2 ) );
    
    add ( y0 = new LineAtomic ( "y0" ) );
    
    addCoupling ( this, "tension0", z0, "tension" );
    addCoupling ( this, "tension1", z1, "tension" );
    addCoupling ( this, "tension2", z2, "tension" );
    
    addCoupling ( z0, "ostate", x0, "state" ); 
    addCoupling ( x0, "ostate", y0, "state" );
    addCoupling ( z1, "ostate", x1, "state" ); 
    addCoupling ( x1, "ostate", y0, "state" );
    addCoupling ( z2, "ostate", x2, "state" ); 
    addCoupling ( x2, "ostate", y0, "state" );
    addCoupling ( y0, "ostate", this, "state" );
    
    addCoupling ( z0, "log", this, "log" );
    addCoupling ( x0, "log", this, "log" );
    addCoupling ( z1, "log", this, "log" );
    addCoupling ( x1, "log", this, "log" );
    addCoupling ( z2, "log", this, "log" );
    addCoupling ( x2, "log", this, "log" );
    addCoupling ( y0, "log", this, "log" );
    
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(385, 537);
        ((ViewableComponent)withName("SensorController z2 (13.0)")).setPreferredLocation(new Point(-11, 297));
        ((ViewableComponent)withName("LineController y0")).setPreferredLocation(new Point(1, 431));
        ((ViewableComponent)withName("SensorController z1 (13.0)")).setPreferredLocation(new Point(-13, 165));
        ((ViewableComponent)withName("SegmentController x2")).setPreferredLocation(new Point(-10, 362));
        ((ViewableComponent)withName("SegmentController x1")).setPreferredLocation(new Point(-13, 228));
        ((ViewableComponent)withName("SegmentController x0")).setPreferredLocation(new Point(-10, 99));
        ((ViewableComponent)withName("SensorController z0 (33.0)")).setPreferredLocation(new Point(-11, 37));
    }
}
