package Component.Devs.control;


import Component.Devs.registrator.RegistratorController;
import java.awt.Dimension;
import java.awt.Point;
import java.io.BufferedWriter;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class ControlController extends ViewableDigraph	{

  private SensorController z0;
  private SensorController z1;
  private SensorController z2;
  
  private SegmentController x0;
  private SegmentController x1;
  private SegmentController x2;
  
  private LineController y0;
  
  public ControlController ( String n ) {	
		super ( String. format ( "ControlController %s", n ) );

    addInport ( "tension0" );
    addInport ( "tension1" );
    addInport ( "tension2" );
    
    addOutport ( "state" );
    
    addOutport ( "log" );
    
    add ( z0 = new SensorController ( "z0", 33 ) );
    add ( z1 = new SensorController ( "z1", 13 ) );
    add ( z2 = new SensorController ( "z2", 13 ) );
    
    add ( x0 = new SegmentController ( "x0", 0 ) );
    add ( x1 = new SegmentController ( "x1", 1 ) );
    add ( x2 = new SegmentController ( "x2", 2 ) );
    
    add ( y0 = new LineController ( "y0" ) );
    
    addCoupling ( this, "tension0", z0, "tension" );
    addCoupling ( this, "tension1", z1, "tension" );
    addCoupling ( this, "tension2", z2, "tension" );
    
    addCoupling ( z0, "ostate", x0, "state" ); 
    addCoupling ( x0, "ostate", y0, "state" );
    addCoupling ( z1, "ostate", x1, "state" ); 
    addCoupling ( x1, "ostate", y0, "state" );
    addCoupling ( z2, "ostate", x2, "state" ); 
    addCoupling ( x2, "ostate", y0, "state" );
    addCoupling ( y0, "ostate", this, "state" );
    
    addCoupling ( z0, "log", this, "log" );
    addCoupling ( x0, "log", this, "log" );
    addCoupling ( z1, "log", this, "log" );
    addCoupling ( x1, "log", this, "log" );
    addCoupling ( z2, "log", this, "log" );
    addCoupling ( x2, "log", this, "log" );
    addCoupling ( y0, "log", this, "log" );
    
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(859, 488);
        ((ViewableComponent)withName("SensorController z2 (13.0)")).setPreferredLocation(new Point(6, 297));
        ((ViewableComponent)withName("LineController y0")).setPreferredLocation(new Point(535, 202));
        ((ViewableComponent)withName("SensorController z1 (13.0)")).setPreferredLocation(new Point(5, 168));
        ((ViewableComponent)withName("SegmentController x2")).setPreferredLocation(new Point(276, 297));
        ((ViewableComponent)withName("SegmentController x1")).setPreferredLocation(new Point(276, 168));
        ((ViewableComponent)withName("SegmentController x0")).setPreferredLocation(new Point(280, 39));
        ((ViewableComponent)withName("SensorController z0 (33.0)")).setPreferredLocation(new Point(4, 37));
    }
}
